apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: mnist-prod
spec:
  name: mnist-prod
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: classifier
          image: davidhershey/seldon-mnist:1.3
    graph:
      children: []
      parameters:
        - name: det_master
          type: STRING
          value: "DET_MASTER_ADDR"
        - name: model_name
          type: STRING
          value: "mnist-prod"
      endpoint:
        type: REST
      name: classifier
      type: MODEL
    name: mnist-prod
    replicas: 1
