apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: dogcat-deploy
  namespace: seldon
spec:
  name: dogcat-deploy
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: dogcat-deploy-container
          image: gcr.io/determined-ai/seldon/image-classification-model:1.0
    graph:
      name: dogcat-deploy-container
      type: MODEL
      parameters:
        - name: det_master
          type: STRING
          value: "DETERMINED_HOST"
        - name: model_name
          type: STRING
          value: "dogcat-model"
        - name: user
          type: STRING
          value: "determined"
        - name: password
          type: STRING
          value: "xxx"
    name: default
