description: object_detection_const_hp_distributed
data:
  url: https://determined-ai-public-datasets.s3-us-west-2.amazonaws.com/PennFudanPed/PennFudanPed.zip
entrypoint: model_def:ObjectDetectionModel
hyperparameters:
  global_batch_size: 32
  learning_rate: 0.01
  momentum: 0.8
  weight_decay: 0.0005
min_validation_period:
  epochs: 1
records_per_epoch: 136
resources:
  slots_per_trial: 8
searcher:
  max_length:
    epochs: 4
  metric: val_avg_iou
  name: single
  smaller_is_better: false
